apply plugin: 'com.android.application'

//
// build.gradle in TeamCode
//
// Most of the definitions for building your module reside in a common, shared
// file 'build.common.gradle'. Being factored in this way makes it easier to
// integrate updates to the FTC into your code. If you really need to customize
// the build definitions, you can place those customizations in this file, but
// please think carefully as to whether such customizations are really necessary
// before doing so.


// Custom definitions may go here

// Include common definitions from above.
buildscript {
    repositories {
        mavenCentral()
        google()
        maven {
            url "https://repo.dairy.foundation/releases"
        }
    }
    dependencies {
        classpath "dev.frozenmilk:Load:0.3.1"
    }
}

apply from: '../build.common.gradle'
apply from: '../build.dependencies.gradle'
apply plugin: 'dev.frozenmilk.sinister.sloth.load'

android {
    namespace = 'org.firstinspires.ftc.teamcode'
    compileSdk 34

    packagingOptions {
        jniLibs.useLegacyPackaging true
    }
}

repositories {
    maven {
        url = 'https://maven.brott.dev/'
    }
    maven {
        url = "https://repo.dairy.foundation/releases"
    }
    maven {
        url = "https://repo.dairy.foundation/snapshots"
    }
    maven {
        url = "https://mymaven.bylazar.com/releases"
    }
}

dependencies {
    implementation project(':FtcRobotController')
    implementation("com.acmerobotics.roadrunner:ftc:0.1.25"){
        exclude group: "com.acmerobotics.dashboard"
    }
    implementation("com.acmerobotics.roadrunner:core:1.0.1"){
        exclude group: "com.acmerobotics.dashboard"
    }
    implementation("dev.frozenmilk.sinister:Sloth:0.3.1")
    implementation("com.acmerobotics.slothboard:dashboard:0.3.1+0.6.0")
    implementation("com.pedropathing:revhub:3.0.0")
    implementation("com.pedropathing:tuning:1.0.0")
    implementation("com.pedropathing.ivy:pedro:1.1.1")
}

afterEvaluate {
    def debugRuntimeJars = configurations.debugRuntimeClasspath.incoming.artifactView {
        attributes {
            attribute(
                    Attribute.of("artifactType", String),
                    "android-classes-jar"
            )
        }
    }.files

    tasks.register("exportAutoPath", JavaExec) {
        dependsOn("compileDebugJavaWithJavac")
        group = "application"
        description = "Exports the example autonomous to a Pedro Visualizer .pp file"
        mainClass = "org.firstinspires.ftc.teamcode.auto.utils.ExportAutoPath"
        classpath = files(
                tasks.named("compileDebugJavaWithJavac").get().destinationDirectory
        ) + debugRuntimeJars
        workingDir = rootProject.projectDir
        if (project.hasProperty("ppOutput")) {
            args(project.property("ppOutput"))
        }
    }
}
